name: 자동 marge

on:
  pull_request_review:
    types: [submitted]

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Set up GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y jq gh

      - name: PR 번호 확인
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [[ "$GITHUB_EVENT_NAME" == "pull_request_review" ]]; then
            PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          else
            echo "지원되지 않는 이벤트 타입입니다: $GITHUB_EVENT_NAME"
            exit 1
          fi

      - name: review_check_result.txt 파일 다운로드
        uses: actions/download-artifact@v3
        with:
          name: review-check-result

      - name: review_check_result.txt 값 확인
        id: check-result
        run: |
          if grep -q "true" review_check_result.txt; then
            echo "result=true" >> $GITHUB_ENV
          else
            echo "result=false" >> $GITHUB_ENV
          fi

      - name: Pull Request 자동 marge
        if: ${{ env.result == 'true' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X PUT -H "Authorization: token $GITHUB_TOKEN" \
               -H "Accept: application/vnd.github.v3+json" \
               "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER/merge" \
               -d '{"merge_method":"merge"}'
