name: auto-merge

on:
  pull_request_review:
    types: [submitted]

jobs:
  auto-merge:
    needs: review-check # review-check 워크플로우의 결과를 의존
    runs-on: ubuntu-latest

    steps:
      - name: Set up GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y jq gh

      - name: 코드 체크아웃
        uses: actions/checkout@v4

      - name: PR 번호 확인
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          echo "PR 번호: $PR_NUMBER"
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV

      - name: Pull Request 자동 병합
        if: ${{ needs.review-check.outputs.approved == 'true' }} # 리뷰 상태 확인 결과를 기반으로 병합 여부 결정
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ env.PR_NUMBER }}
        run: |
          curl -X PUT -H "Authorization: token $GITHUB_TOKEN" \
               -H "Accept: application/vnd.github.v3+json" \
               "https://api.github.com/repos/${{ github.repository }}/pulls/${{ env.PR_NUMBER }}/merge" \
               -d '{"merge_method":"merge"}'
