name: Pull Request 자동 병합

on:
  pull_request_review:
    types: [submitted]  
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Set up GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y jq gh

      - name: 코드 체크아웃
        uses: actions/checkout@v4

      - name: Pull Request 병합 확인
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # 환경 변수에서 approved 상태 확인
          if [[ "${{ github.event.workflow_run.conclusion }}" != "success" ]]; then
            echo "이전 워크플로우가 성공적으로 완료되지 않았습니다. 병합 중단."
            exit 1
          fi

          # approved 환경 변수가 true인지 확인
          if [[ "${{ env.approved }}" != "true" ]]; then
            echo "Pull Request 조건이 충족되지 않았습니다. 병합 중단."
            exit 1
          fi

          echo "Pull Request 조건이 충족되었습니다. 병합을 시작합니다."

      - name: Pull Request 병합
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "PR 병합 진행 중..."
          PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          curl -X PUT -H "Authorization: token $GITHUB_TOKEN" \
               -H "Accept: application/vnd.github.v3+json" \
               "https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER}/merge" \
               -d '{"merge_method":"merge"}'
