name: auto-merge

on:
  pull_request_review:
    types: [submitted]

jobs:
  auto-merge:
    needs: review-check
    runs-on: ubuntu-latest

    steps:
      - name: Set up GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y jq gh

      - name: 디버깅: needs 값 확인
        run: |
          echo "Review Check Output: ${{ needs.review-check.outputs.approved }}"
          echo "GitHub Event: ${{ github.event_name }}"
          echo "Pull Request Number: ${{ github.event.pull_request.number }}"

      - name: Pull Request 자동 병합
        if: ${{ needs.review-check.outputs.approved == 'true' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          echo "병합 조건 충족. PR 병합 진행 중..."
          curl -X PUT -H "Authorization: token $GITHUB_TOKEN" \
               -H "Accept: application/vnd.github.v3+json" \
               "https://api.github.com/repos/${{ github.repository }}/pulls/${{ env.PR_NUMBER }}/merge" \
               -d '{"merge_method":"merge"}'

      - name: 조건 미충족
        if: ${{ needs.review-check.outputs.approved != 'true' }}
        run: echo "병합 조건 미충족. 작업 종료."
