name: auto-merge

on:
  workflow_run:
    workflows:
      - review-check  # 완료를 기다릴 워크플로우 이름
    types:
      - completed      # 워크플로우가 완료되었을 때만 실행

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Set up GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y jq gh

      - name: 디버깅: 이벤트 값 확인
        run: |
          echo "GitHub Event: ${{ github.event.workflow_run.conclusion }}"
          echo "GitHub Workflow Name: ${{ github.event.workflow_run.name }}"

      - name: Pull Request 자동 병합
        if: ${{ github.event.workflow_run.conclusion == 'success' }} # 이전 워크플로우가 성공했는지 확인
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.workflow_run.pull_requests[0].number }}
        run: |
          echo "병합 조건 충족. PR 병합 진행 중..."
          curl -X PUT -H "Authorization: token $GITHUB_TOKEN" \
               -H "Accept: application/vnd.github.v3+json" \
               "https://api.github.com/repos/${{ github.repository }}/pulls/${{ env.PR_NUMBER }}/merge" \
               -d '{"merge_method":"merge"}'

      - name: 조건 미충족
        if: ${{ github.event.workflow_run.conclusion != 'success' }}
        run: echo "병합 조건 미충족. 작업 종료."
