name: Auto Merge on review-check Success

on:
  workflow_run:
    workflows:
      - review-check  # review-check 워크플로우 완료를 트리거로 설정
    types:
      - completed      # review-check 완료 시 실행

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Set up GitHub CLI and jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq gh

      - name: 코드 체크아웃
        uses: actions/checkout@v4

      - name: Check review-check Result
        # review-check의 결과를 확인
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # review-check 워크플로우 결과가 approved=true인지 확인
          if [[ "${{ github.event.workflow_run.conclusion }}" != "success" ]]; then
            echo "review-check Validation 결과가 조건을 충족하지 못했습니다. 병합 중단."
            exit 1
          fi
          echo "review-check Validation 조건 충족. 병합을 진행합니다."

      - name: Merge the Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Pull Request 번호 확인
          PR_NUMBER=$(jq --raw-output '.pull_requests[0].number' <<< "${{ toJson(github.event.workflow_run.pull_requests) }}")
          echo "PR 번호: $PR_NUMBER"

          # Pull Request 병합
          curl -X PUT -H "Authorization: token $GITHUB_TOKEN" \
               -H "Accept: application/vnd.github.v3+json" \
               "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER/merge" \
               -d '{"merge_method":"merge"}'

          echo "PR #$PR_NUMBER 병합 완료."
