name: Pull Request Validation

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  validate-condition:
    runs-on: ubuntu-latest

    steps:
      - name: Set up GitHub CLI and jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq gh

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Validate Condition
        run: |
          # 조건: 기본 값으로 항상 true 반환
          echo "Condition met: Default True for testing."
          echo "approved=true" >> $GITHUB_ENV

      - name: Output Result
        run: |
          echo "Condition Result: ${{ env.approved }}"
