name: Pull Request Validation

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  validate-condition:
    runs-on: ubuntu-latest

    steps:
      - name: Set up GitHub CLI and jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq gh

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Validate Condition
        run: |
          # 간단한 조건: 1+1 == 2 확인
          if [[ $((1 + 1)) -eq 3 ]]; then
            echo "Condition met: 1+1 equals 2."
            echo "approved=true" >> $GITHUB_ENV
          else
            echo "Condition not met: 1+1 does not equal 2."
            echo "approved=false" >> $GITHUB_ENV
            exit 1
          fi

      - name: Output Result
        run: |
          echo "Condition Result: ${{ env.approved }}"
