name: review-check

on:
  pull_request_review:
    types: [submitted]

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Set up GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y jq gh

      - name: 코드 체크아웃
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: PR 승인 상태 확인
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # 이벤트 타입에 따라 PR 번호 가져오기
          if [[ "$GITHUB_EVENT_NAME" == "pull_request" ]]; then
            PR_NUMBER=$(jq --raw-output .number "$GITHUB_EVENT_PATH")
          elif [[ "$GITHUB_EVENT_NAME" == "pull_request_review" ]]; then
            PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          else
            echo "지원되지 않는 이벤트 타입입니다: $GITHUB_EVENT_NAME"
            exit 1
          fi

          echo "PR 번호: $PR_NUMBER"

          if [ -z "$PR_NUMBER" ]; then
            echo "Error: PR 번호를 가져오지 못했습니다."
            exit 1
          fi

          # 리뷰어 정보 가져오기
          REVIEWERS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER/requested_reviewers" | jq '.reviewers | length')

          echo "리뷰어 수: $REVIEWERS"

          if [ "$REVIEWERS" -eq 0 ]; then
            echo "리뷰어가 없으므로 자동 병합을 수행하지 않습니다."
            exit 0
          fi

          # 리뷰 상태 확인
          REVIEWS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER/reviews")
          APPROVAL_COUNT=$(echo "$REVIEWS" | jq '[.[] | select(.state == "APPROVED")] | length')
          echo "승인된 리뷰어 수: $APPROVAL_COUNT"

          REQUIRED_APPROVALS=2  # 필요한 승인 수

          if [ "$APPROVAL_COUNT" -ge "$REQUIRED_APPROVALS" ]; then
            echo "All required approvals have been met."
            echo "approved=true" >> $GITHUB_ENV
          else
            echo "Not all required approvals have been met."
            echo "approved=false" >> $GITHUB_ENV
          fi

      - name: 조건 충족 시 결과 기록
        if: ${{ env.approved == 'true' && github.event.pull_request.base.ref != 'master' }}
        run: |
          echo "true" > review_check_result.txt

      - name: 조건 미충족 시 결과 기록
        if: ${{ env.approved != 'true' || github.event.pull_request.base.ref == 'master' }}
        run: |
          echo "false" > review_check_result.txt

      - name: 결과 업로드
        uses: actions/upload-artifact@v3
        with:
          name: review-check-result
          path: review_check_result.txt
