name: review-check

on:
  pull_request_review:
    types: [submitted]

jobs:
  review-check:
    runs-on: ubuntu-latest
    outputs:
      approved: ${{ steps.check.outputs.approved }} # 승인 여부를 출력 변수로 설정

    steps:
      - name: Set up GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y jq gh

      - name: 코드 체크아웃
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: PR 승인 상태 확인
        id: check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # PR 번호 가져오기
          PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          echo "PR 번호: $PR_NUMBER"

          # 리뷰 상태 확인
          REVIEWS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER/reviews")
          APPROVAL_COUNT=$(echo "$REVIEWS" | jq '[.[] | select(.state == "APPROVED")] | length')
          echo "승인된 리뷰어 수: $APPROVAL_COUNT"

          REQUIRED_APPROVALS=2  # 필요한 승인 수
          if [ "$APPROVAL_COUNT" -ge "$REQUIRED_APPROVALS" ]; then
            echo "::set-output name=approved::true"
          else
            echo "::set-output name=approved::false"
          fi
