name: 코드 테스트 자동화

on:
  push:
    branches: [main, develop, feature/*]
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' 
          java-version: '22' 
          
      - name: Gradle 설치 및 테스트 실행
        run: |
          sudo apt-get update
          sudo apt-get install -y gradle
          gradle clean test

      # 4. Gradle 빌드 및 테스트 실행
      - name: Gradle 빌드 및 테스트 실행
        working-directory: ./app  # `build.gradle.kts`가 있는 디렉터리로 이동
        run: |
          ./gradlew clean test

      # 5. 테스트 결과 출력
      - name: 테스트 결과 출력
        run: |
          echo "테스트 완료"

