name: 코드 테스트 자동화

on:
  push:
    branches: [main, develop, feature/*]
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' 
          java-version: '22' 
          
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: 테스트 실행
        run: |
          mvn clean test -Dsurefire.includes=src/Test/**/*.java

      - name: 테스트 결과 기반 환경 변수 설정
        id: set-env
        run: |
          if [ $? -eq 0 ]; then
            echo "모든 테스트가 성공적으로 통과했습니다."
            echo "TEST_RESULT=true" >> $GITHUB_ENV
          else
            echo "테스트 실패가 발생했습니다."
            echo "TEST_RESULT=false" >> $GITHUB_ENV

