name: 코드 테스트 자동화

on:
  push:
    branches: [main, develop, feature/*]
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' 
          java-version: '22' 
          
      - name: Gradle 캐시 삭제
        run: |
          rm -rf ~/.gradle/caches

      - name: Gradle 빌드 및 테스트 실행
        working-directory: ./app
        run: |
          chmod +x gradlew
          ./gradlew clean test --stacktrace --info

      # 5. 테스트 결과 출력
      - name: 테스트 결과 출력
        run: |
          echo "테스트 완료"

